# -*- coding: utf-8 -*-
"""Projeto_Tabela_Brasileirao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LmuLZXmTmfMOOv4rEsY0hX8-9e9YO_QX
"""

import requests
import pandas as pd
from bs4 import BeautifulSoup

ano = int(input('Qual ano vc deseja acessar: '))
serie = input('Qual serie do Brasileirão vc gostaria de ver: ')
url = f'https://www.cbf.com.br/futebol-brasileiro/competicoes/campeonato-brasileiro-serie-{serie}/{ano}'

pagina = requests.get(url)
soup = BeautifulSoup(pagina.content, 'html.parser')
indicador = soup.select('.expand-trigger')
times = list(map(lambda time:time.select('.hidden-xs')[0].text, indicador))

print(f'O time campeão foi o {times[0]}')
print(f'\nOs times rebaixados foram as equipes {times[16]}, {times[17]}, {times[18]}, {times[19]}')

pd.DataFrame(times)